### PR TITLE
Faster requests

### PR DESCRIPTION
**Pull request by chrisstpierre**

### CODE REVIEW

**Comment by judepereira** [comment]
@chrisstpierre what's the difference in terms of requests per second before and after your patch?

**Comment by chrisstpierre** [comment]
> @chrisstpierre what's the difference in terms of requests per second before and after your patch?

It's about doubled. So ~140 rq/second. The rq/second is still a lot higher for just the `platform-engine` or just `http`, but slower when coupled. I'm not sure theres much more we could do really except adding multiple process.

**Comment by judepereira** [comment]
@chrisstpierre What's the throughput of the gateway without the engine? What happens if you replace the engine with a plain (but really fast) Apache Tomcat server? I'm trying to understand the following:
1. Is the gateway independently slow (without making any HTTP calls outside)
2. How much does the throughput drop after substituting the engine with an instance of Apache Tomcat (Apache Tomcat because it can do 16k rps easily)?
3. How much does the throughput drop after hooking the gateway to the engine, but not executing any story in the engine?
4. Same as 3, except that we're executing a simple story in the engine

Throughput numbers for 1 to 4 above would help us understand the bottleneck more appropriately, and have some reference for in the future.

**Comment by chrisstpierre** [comment]
> @chrisstpierre What's the throughput of the gateway without the engine? What happens if you replace the engine with a plain (but really fast) Apache Tomcat server? I'm trying to understand the following:
> 
> 1. Is the gateway independently slow (without making any HTTP calls outside)
> 2. How much does the throughput drop after substituting the engine with an instance of Apache Tomcat (Apache Tomcat because it can do 16k rps easily)?
> 3. How much does the throughput drop after hooking the gateway to the engine, but not executing any story in the engine?
> 4. Same as 3, except that we're executing a simple story in the engine
> 
> Throughput numbers for 1 to 4 above would help us understand the bottleneck more appropriately, and have some reference for in the future.

Also I tested the platform also against a Tornado proxy server and got similar results so I don't think theres much else we can do there. But anyways I'll get these answers to you tomorrow.

**Comment by chrisstpierre** [comment]
Good news! Having the intellij console open while benchmarking was adding significant latency due to the logs. Disabling logging (even just minimizing intellij) increases the speed quite a bit. This wasn't clear before even though I specifically timed logging.

We should move the engine & the gateway to async logging like aiologger, so logging does not affect execution time. Frustrum / standard logger is synchronous. (apparently not in python 3.8 beta)

So we are actually getting getting 550rq/s through the gatway now. Compared with 700rq/s straight to the engine. Thats a lot better. This is with a simple http `hello world` story. So throughput drop is roughly 700 -> 550.

Let me know if you still want me to answer your other questions. However, it seems like we can move to async logging & then wrap this up for now.

> Is the gateway independently slow (without making any HTTP calls outside)
If the platform-engine isn't running, so we have "Unable to Resolve" then we get 750rq/sec. With no http calls at all (simple single thread processing we have something like 2000 rq/s).

**Comment by judepereira** [comment]
Sounds good. Logging to stdout is slow, but I doubt it's the case in production (we can test this later).

Btw, tornado can do 2.5k per second with the engine directly right? In this case, why does the engine drop to 750 when a story is actually running?

**Comment by chrisstpierre** [comment]
> Sounds good. Logging to stdout is slow, but I doubt it's the case in production (we can test this later).
> 
> Btw, tornado can do 2.5k per second with the engine directly right? In this case, why does the engine drop to 750 when a story is actually running?

So I get 1450 with a fresh Tornado Server. And 700 for our server processing a story. Previously I determined that 1/2 - 3/4 of the story execution time goes to synchronous processing (tree processing, logging, etc), so it makes sense that 1450 drops to 700 for that. 

I get 3400 when I add multi-processing.

**Pull request merged**
